### PR TITLE
Add daily limit

### PR DESCRIPTION
**Pull request by WillySchu**
Also a few bugs with the checks, it was checking if it was over the intervalThreshold and not allowedReqsPerInterval

---
This change is [Reviewable](https://reviewable.io/reviews/metricstory/scalable-rate-limiter/2)

### CODE REVIEW

**Comment by WillySchu** [comment]
Updated README to fix a few typos and add syntax highlighting.

**Comment by nutterbrand** [comment]
*[rl.lua, line 15 at r1](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2#-K_6qXiT_r-ZnkgyIntZ:-K_6qXiT_r-ZnkgyInt_:bz3if31) ([raw file](https://github.com/metricstory/scalable-rate-limiter/blob/8954f506444f1ef352ca39cbe7ef5b46badedaa1/rl.lua#L15)):*
> ```Lua
> if dailyLimit > 0 then
>   local dailyCount = tonumber(redis.call('INCR', dailyKey))
>   redis.call('EXPIRE', dailyKey, dailyTTL)
> ```

I need more clarification on what this is doing. Here are a few things I think we should do:
1) Since we moved this script to it's own file, we now have the chance to document it :), but i'm not sure the syntax on documenting LUA scripts.
2) The DailyKey, dailyCount, and dailyTTL are to expire the quota count PST correct? If so, how does it work when we keep settings EXPIRE on the dailyTTL everytime we call this function? I may be missing something, but I would have put this logic in the node file to redis.call('EXPIRE', userKey, secondsUntilMidnightPST) and then update the expire to the new secondsUntilMidnightPST for that user key (or check if it is already set).
3) It looks like dailyTTL gets set right now in the construction and I'm not sure what it is doing: "dailyTTL = 60 * 60 * 24 * 31", // roughly a month" since this looks like the number of seconds for a month.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2)*

**Comment by nutterbrand** [comment]
*[README.md, line 29 at r1](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2#-K_6sXDFHBfXRpqIECLA:-K_6sXDFHBfXRpqIECLB:b-rytv1l) ([raw file](https://github.com/metricstory/scalable-rate-limiter/blob/8954f506444f1ef352ca39cbe7ef5b46badedaa1/README.md#L29)):*
> ```Markdown
> * @param {Integer} allowedTokensPerInterval The number of allowed tokens a user can use (API requests) in time period
> * @param {Integer} intervalThreshold The interval threshold to wait before
> * @param {String}  rateLimiterNameSpace redis namespace of the rate limiter: default: '.rate.limiter'
> ```

Update the example to show the new parameters we can use for quota :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2)*

**Comment by nutterbrand** [comment]
*[README.md, line 68 at r1](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2#-K_6sdyB-RChhONwEBCn:-K_6sdyB-RChhONwEBCo:bv7hita) ([raw file](https://github.com/metricstory/scalable-rate-limiter/blob/8954f506444f1ef352ca39cbe7ef5b46badedaa1/README.md#L68)):*
> ```Markdown
> ```
> 1) Implement daily API quota check for a user
> 2) Add tests to the rate limiter
> ```

Update the Wish List and take out #1 and #2 since you knocked em out today. Good work man!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2)*

**Comment by nutterbrand** [comment]
*[package.json, line 36 at r1](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2#-K_6srsV2fX4oUXBrFun:-K_6srsW5jQxNoYDpPZB:b-fnzilg) ([raw file](https://github.com/metricstory/scalable-rate-limiter/blob/8954f506444f1ef352ca39cbe7ef5b46badedaa1/package.json#L36)):*
> ```JSON
>   "dependencies": {
>     "fs": "0.0.1-security",
>     "moment": "^2.17.1",
> ```

You can put a * in the minor version: 2.17.* and moment-timezone: 0.5.*. This way our packages will stay up to-date with minor patches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2)*

**Comment by nutterbrand** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2)*

**Comment by WillySchu** [comment]
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[rl.lua, line 15 at r1](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2#-K_6qXiT_r-ZnkgyIntZ:-K_B3Qo5x6amojyVsoVd:b-87rb98) ([raw file](https://github.com/metricstory/scalable-rate-limiter/blob/8954f506444f1ef352ca39cbe7ef5b46badedaa1/rl.lua#L15)):*
<details><summary><i>Previously, nutterbrand (Brandon Nutter) wrote…</i></summary><blockquote>

I need more clarification on what this is doing. Here are a few things I think we should do:
1) Since we moved this script to it's own file, we now have the chance to document it :), but i'm not sure the syntax on documenting LUA scripts.
2) The DailyKey, dailyCount, and dailyTTL are to expire the quota count PST correct? If so, how does it work when we keep settings EXPIRE on the dailyTTL everytime we call this function? I may be missing something, but I would have put this logic in the node file to redis.call('EXPIRE', userKey, secondsUntilMidnightPST) and then update the expire to the new secondsUntilMidnightPST for that user key (or check if it is already set).
3) It looks like dailyTTL gets set right now in the construction and I'm not sure what it is doing: "dailyTTL = 60 * 60 * 24 * 31", // roughly a month" since this looks like the number of seconds for a month.
</blockquote></details>

As the dailyCount uses the date itself as a key it is unnecessary to expire it at all. When the date rolls over a new counter will automatically be created with the new date as part of its key. The TTL is there just to make sure that the counts are deleted eventually, but we can keep them around for a while for record keeping. As of right now, the daily counts are kept around for 'roughly a month'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2)*

**Comment by nutterbrand** [comment]
*[rl.lua, line 15 at r1](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2#-K_6qXiT_r-ZnkgyIntZ:-K_B4s9J_5098X7jJA1F:buosv5w) ([raw file](https://github.com/metricstory/scalable-rate-limiter/blob/8954f506444f1ef352ca39cbe7ef5b46badedaa1/rl.lua#L15)):*
<details><summary><i>Previously, WillySchu (Will Schumacher) wrote…</i></summary><blockquote>

As the dailyCount uses the date itself as a key it is unnecessary to expire it at all. When the date rolls over a new counter will automatically be created with the new date as part of its key. The TTL is there just to make sure that the counts are deleted eventually, but we can keep them around for a while for record keeping. As of right now, the daily counts are kept around for 'roughly a month'.
</blockquote></details>

Ah, that makes sense so after midnight PST we will have a new key. You then expire that key in roughly a month. -- makes sense :100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2)*

**Comment by nutterbrand** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/metricstory/scalable-rate-limiter/2#-:-K_B58PxHmI8fx3PRbCL:bnfp4nl)*

**Pull request merged**
